# Generated by Django 5.1.3 on 2024-12-03 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire', '0002_alter_firefighters_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firefighters',
            name='station',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
